defaults: &defaults
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 25
  database: elo_league_development
  username: <%= ENV['USERNAME'] %>
  password: 
  min_messages: warning
  host: localhost

development:
  <<: *defaults

test: &test
  <<: *defaults
  database: elo_league_test

production:
  <<: *defaults
  database: elo_league_test

